### PR TITLE
Use DagArchive to get dag with structured files

### PR DESCRIPTION
**Pull request by rht**
Addresses #6.

### CODE REVIEW

**Comment by noffle** [comment]
Awesome PR! :tada:

A few things I noticed:

1. If use a path like /ipfs/<hash>, it will try to write the data to `/ipfs/...` on my local drive. As I understand it `/ipfs` and `/ipns` are valid network IPFS paths regardless of whether the user has either mounted locally. (sanity check: cc @whyrusleeping)

2. This breaks downloading individual files within directories. (e.g. `ipget QmeZnaoktRvs3Ek8pQNyj8BbrkKuJ5Ez6JHi32dazL7cEJ/rfc1.txt`)  The extractor assumes the `QmeZn..` directory exists and tries to write within that directory. I think we should keep the current functionality (save to local directory using name in the last segment of the ipfs path), but do full directory writing when a directory is what's asked for.

3. The issue with extraction not giving progress stinks. For now, at least, you can put a `io.TeeReader` between the Reader returned by `cat()` and the one passed into `extractor.Extract()` to still see progress go to 100% upon command completion, and, presumably, once `extractor` reports progress on that reader some day.

**Comment by jbenet** [comment]
> As I understand it /ipfs and /ipns are valid network IPFS paths regardless of whether the user has either mounted locally. (sanity check: cc @whyrusleeping)

that's right. _if the user chooses to_ output to a local fs path like `/ipfs/<some-path>` though, there's not much we can/should do. they may be putting all their stuff in `/ipfs` and not intending to mount... def confusing but dont think we should overstep and say "no don't use your paths that way". (_if_ the user chooses to, we shouldn't be outputting there by default)

> I think we should keep the current functionality (save to local directory using name in the last segment of the ipfs path), but do full directory writing when a directory is what's asked for.

Yeah, that SGTM. the other (preserve the original path making directories along the way-- might be an option. though could be misleading if it doesn't download _everything_ under a dir with a given hash)

**Comment by noffle** [comment]
> if the user chooses to output to a local fs path like /ipfs/<some-path> though, there's not much we can/should do.

Yes, agreed. I meant this only in the context of an address to download *from*.

**Comment by rht** [comment]
@noffle 2,3,4 fixed. For 1, it is also the case in current `ipfs get`.

**Comment by noffle** [comment]
@rht awesome changes! Thanks for the improvements.

**Pull request merged**
